name: Deploy Backend to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ASG_NAME: ${{ secrets.BACKEND_ASG_NAME }}
  ECR_REPOSITORY: ${{ secrets.BACKEND_ECR_REPOSITORY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Fetch database credentials from AWS Secrets Manager
        id: db-credentials
        run: |
          DB_CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id "djangobnb/dev/database" --query SecretString --output text)
          DB_PASSWORD=$(echo $DB_CREDENTIALS | jq -r '.password')
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

      - name: Fetch Django secrets from AWS Secrets Manager
        id: django-secrets
        run: |
          DJANGO_SECRETS=$(aws secretsmanager get-secret-value --secret-id "djangobnb/dev/django" --query SecretString --output text)
          DJANGO_SECRET_KEY=$(echo $DJANGO_SECRETS | jq -r '.secret_key')
          DJANGO_DEBUG=$(echo $DJANGO_SECRETS | jq -r '.debug')
          echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" >> $GITHUB_ENV
          echo "DJANGO_DEBUG=$DJANGO_DEBUG" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=latest
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

          echo "Building Docker image: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          # Also push commit SHA for rollback capability
          docker tag $IMAGE_URI ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Run database migrations
        run: |
          # Create a temporary container to run migrations
          docker run --rm \
            -e DB_PASSWORD="${{ env.DB_PASSWORD }}" \
            -e SECRET_KEY="${{ env.DJANGO_SECRET_KEY }}" \
            -e DJANGO_DEBUG="${{ env.DJANGO_DEBUG }}" \
            -e SQL_ENGINE="django.db.backends.postgresql" \
            -e SQL_DATABASE="djangobnb" \
            -e SQL_USER="djangobnb" \
            -e SQL_HOST="${{ secrets.RDS_ENDPOINT }}" \
            -e SQL_PORT="5432" \
            ${{ env.IMAGE_URI }} \
            python manage.py migrate

      - name: Prepare user-data script
        run: |
          cat > user-data.sh <<'EOF'
          #!/bin/bash
          set -euo pipefail

          apt-get update -y
          apt-get install -y ca-certificates curl gnupg unzip lsb-release git nginx jq docker.io python3 python3-pip python3-venv postgresql-client

          systemctl enable docker
          systemctl start docker

          # AWS CLI v2
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          ./aws/install
          rm -rf awscliv2.zip aws

          # Amazon SSM Agent
          snap install amazon-ssm-agent --classic
          systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
          systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service

          mkdir -p /opt/djangobnb-backend
          chown ubuntu:ubuntu /opt/djangobnb-backend

          # Get region using IMDSv2
          TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          REGION=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"

          # Get secrets from Secrets Manager
          DB_CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id "djangobnb/dev/database" --query SecretString --output text)
          DJANGO_SECRETS=$(aws secretsmanager get-secret-value --secret-id "djangobnb/dev/django" --query SecretString --output text)
          
          # Parse JSON secrets
          DB_PASSWORD=$(echo $DB_CREDENTIALS | jq -r '.password')
          SECRET_KEY=$(echo $DJANGO_SECRETS | jq -r '.secret_key')
          DEBUG=$(echo $DJANGO_SECRETS | jq -r '.debug')

          # Login & pull
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker pull $ECR_REGISTRY/ECR_REPOSITORY_VALUE:latest

          # Restart container
          docker stop backend-container 2>/dev/null || true
          docker rm backend-container 2>/dev/null || true
          docker run -d --name backend-container --restart=always -p 8000:8000 \
            -e DB_PASSWORD="$DB_PASSWORD" \
            -e SECRET_KEY="$SECRET_KEY" \
            -e DEBUG="$DEBUG" \
            -e SQL_ENGINE="django.db.backends.postgresql" \
            -e SQL_DATABASE="djangobnb" \
            -e SQL_USER="djangobnb" \
            -e SQL_HOST="RDS_ENDPOINT_VALUE" \
            -e SQL_PORT="5432" \
            -e ENVIRONMENT=dev \
            -e ALLOWED_HOSTS="dev-djangobnb-alb-720056700.us-east-1.elb.amazonaws.com,localhost,127.0.0.1" \
            $ECR_REGISTRY/ECR_REPOSITORY_VALUE:latest

          # Nginx reverse proxy
          cat > /etc/nginx/sites-available/default << 'NGINX_EOF'
          server {
              listen 80;
              server_name _;
              client_max_body_size 100M;
              
              location / {
                  proxy_pass http://localhost:8000;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_connect_timeout 60s;
                  proxy_send_timeout 60s;
                  proxy_read_timeout 60s;
              }
              
              location /static/ {
                  alias /opt/djangobnb-backend/static/;
                  expires 1y;
                  add_header Cache-Control "public, immutable";
              }
              
              location /media/ {
                  alias /opt/djangobnb-backend/media/;
                  expires 1y;
                  add_header Cache-Control "public";
              }
          }
          NGINX_EOF

          systemctl restart nginx
          systemctl enable nginx
          EOF

          sed -i "s/ECR_REPOSITORY_VALUE/${{ env.ECR_REPOSITORY }}/g" user-data.sh
          sed -i "s/RDS_ENDPOINT_VALUE/${{ secrets.RDS_ENDPOINT }}/g" user-data.sh

          USER_DATA=$(base64 -w 0 user-data.sh)
          echo "USER_DATA=$USER_DATA" >> $GITHUB_ENV

      - name: Update Launch Template
        run: |
          LAUNCH_TEMPLATE_ID=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names $ASG_NAME \
            --query 'AutoScalingGroups[0].LaunchTemplate.LaunchTemplateId' \
            --output text)

          echo "Updating Launch Template: $LAUNCH_TEMPLATE_ID"

          aws ec2 create-launch-template-version \
            --launch-template-id $LAUNCH_TEMPLATE_ID \
            --source-version '$Latest' \
            --launch-template-data "{\"UserData\":\"$USER_DATA\"}"

      - name: Refresh Auto Scaling Group
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name $ASG_NAME \
            --preferences '{"InstanceWarmup":300,"MinHealthyPercentage":50}'
